name: iv_project_data
description: "IV Project Data"
version: 0.0.5
homepage:
publish_to: none

environment:
  sdk: ^3.10.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  iv_project_model:
    path: ../iv_project_model

  iv_project_repository:
    path: ../iv_project_repository

  iv_project_core:
    path: ../iv_project_core

  iv_project_api_core:
    path: ../iv_project_api_core
  
  equatable: ^2.0.7
  
  flutter_bloc: ^9.1.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
